param vmssVirusScannerName string
param vNetName string
param virusScannerSubnetName string
param vmAdminUsernameSecretName string
param vmAdminPasswordSecretName string
param vmssVirusScannerInstanceCount int
param keyVaultName string
